# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Mon Dec  8 19:56:03 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from MyCentralWidget import *
from Connections import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object, Connections):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(905, 601)
        #self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget = MyCentralWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(360, 370, 271, 181))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 20, 91, 81))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(90, 100, 91, 81))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(0, 100, 91, 81))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 100, 91, 81))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 330, 351, 221))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 20, 111, 101))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(120, 130, 111, 91))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 130, 111, 91))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(240, 130, 111, 91))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(420, 210, 211, 171))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalSlider = QtGui.QSlider(self.groupBox_4)
        self.horizontalSlider.setGeometry(QtCore.QRect(0, 120, 161, 29))
        self.horizontalSlider.setMaximum(180)
        self.horizontalSlider.setProperty("value", 90)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.horizontalSlider.setTickInterval(25)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.verticalSlider = QtGui.QSlider(self.groupBox_4)
        self.verticalSlider.setGeometry(QtCore.QRect(180, 10, 29, 141))
        self.verticalSlider.setMaximum(180)
        self.verticalSlider.setProperty("value", 90)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.verticalSlider.setTickInterval(25)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_10.setGeometry(QtCore.QRect(30, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(140, 140, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(10, 90, 151, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(410, 0, 221, 211))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 30, 211, 51))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_11.setGeometry(QtCore.QRect(130, 140, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(10, 81, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.pushButton_12 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 140, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_13 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(60, 10, 151, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_3.setGeometry(QtCore.QRect(80, 82, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(120, 190, 101, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.frame = QtGui.QFrame(self.groupBox_3)
        self.frame.setGeometry(QtCore.QRect(10, 120, 211, 21))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.radioButton_4 = QtGui.QRadioButton(self.frame)
        self.radioButton_4.setGeometry(QtCore.QRect(140, 0, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.radioButton_2 = QtGui.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(0, 0, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.pushButton_14 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_14.setGeometry(QtCore.QRect(180, 140, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_15.setGeometry(QtCore.QRect(140, 90, 81, 21))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 411, 331))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.sensors = QtGui.QScrollArea(self.centralwidget)
        self.sensors.setGeometry(QtCore.QRect(640, 0, 261, 551))
        self.sensors.setWidgetResizable(True)
        self.sensors.setObjectName(_fromUtf8("sensors"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 259, 549))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.sensors.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuRobot_type = QtGui.QMenu(self.menuSettings)
        self.menuRobot_type.setObjectName(_fromUtf8("menuRobot_type"))
        self.menuAudio = QtGui.QMenu(self.menuSettings)
        self.menuAudio.setObjectName(_fromUtf8("menuAudio"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuadcopter = QtGui.QAction(MainWindow)
        self.actionQuadcopter.setObjectName(_fromUtf8("actionQuadcopter"))
        self.actionTank = QtGui.QAction(MainWindow)
        self.actionTank.setObjectName(_fromUtf8("actionTank"))
        self.actionCar = QtGui.QAction(MainWindow)
        self.actionCar.setObjectName(_fromUtf8("actionCar"))
        self.actionBoat = QtGui.QAction(MainWindow)
        self.actionBoat.setObjectName(_fromUtf8("actionBoat"))
        self.actionWorkspace = QtGui.QAction(MainWindow)
        self.actionWorkspace.setObjectName(_fromUtf8("actionWorkspace"))
        self.actionLanguage = QtGui.QAction(MainWindow)
        self.actionLanguage.setObjectName(_fromUtf8("actionLanguage"))
        self.actionLoop_settings = QtGui.QAction(MainWindow)
        self.actionLoop_settings.setObjectName(_fromUtf8("actionLoop_settings"))
        self.actionVolume = QtGui.QAction(MainWindow)
        self.actionVolume.setObjectName(_fromUtf8("actionVolume"))
        self.menuRobot_type.addAction(self.actionQuadcopter)
        self.menuRobot_type.addAction(self.actionTank)
        self.menuRobot_type.addAction(self.actionCar)
        self.menuRobot_type.addAction(self.actionBoat)
        self.menuAudio.addSeparator()
        self.menuAudio.addAction(self.actionLoop_settings)
        self.menuAudio.addAction(self.actionVolume)
        self.menuSettings.addAction(self.menuRobot_type.menuAction())
        self.menuSettings.addAction(self.actionWorkspace)
        self.menuSettings.addAction(self.actionLanguage)
        self.menuSettings.addAction(self.menuAudio.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Altitude, Yaw", None))
        self.pushButton_3.setText(_translate("MainWindow", "i", None))
        self.pushButton_4.setText(_translate("MainWindow", "k", None))
        self.pushButton.setText(_translate("MainWindow", "j", None))
        self.pushButton_2.setText(_translate("MainWindow", "l", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Robot movement", None))
        self.pushButton_5.setText(_translate("MainWindow", "w", None))
        self.pushButton_6.setText(_translate("MainWindow", "s", None))
        self.pushButton_7.setText(_translate("MainWindow", "a", None))
        self.pushButton_8.setText(_translate("MainWindow", "d", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Camera ", None))
        self.pushButton_9.setText(_translate("MainWindow", "Start recording", None))
        self.pushButton_10.setText(_translate("MainWindow", "Stop recording", None))
        self.label_3.setText(_translate("MainWindow", "X angle", None))
        self.label_4.setText(_translate("MainWindow", "Y angle", None))
        self.label.setText(_translate("MainWindow", "0 [s]", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Audio", None))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Hello, how are you ?", None))
        self.pushButton_11.setText(_translate("MainWindow", "Play", None))
        self.checkBox.setText(_translate("MainWindow", "Listen", None))
        self.pushButton_12.setText(_translate("MainWindow", "Start recording", None))
        self.pushButton_13.setText(_translate("MainWindow", "Stop recording", None))
        self.label_2.setText(_translate("MainWindow", "Language: en", None))
        self.checkBox_3.setText(_translate("MainWindow", "Loop", None))
        self.label_5.setText(_translate("MainWindow", "0 [s]", None))
        self.radioButton_4.setText(_translate("MainWindow", "File", None))
        self.radioButton_2.setText(_translate("MainWindow", "Microphone", None))
        self.pushButton_14.setText(_translate("MainWindow", "Stop", None))
        self.pushButton_15.setText(_translate("MainWindow", "...", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuRobot_type.setTitle(_translate("MainWindow", "Robot type", None))
        self.menuAudio.setTitle(_translate("MainWindow", "Audio", None))
        self.actionQuadcopter.setText(_translate("MainWindow", "quadcopter", None))
        self.actionTank.setText(_translate("MainWindow", "tank", None))
        self.actionCar.setText(_translate("MainWindow", "car", None))
        self.actionBoat.setText(_translate("MainWindow", "boat", None))
        self.actionWorkspace.setText(_translate("MainWindow", "Workspace", None))
        self.actionLanguage.setText(_translate("MainWindow", "Language", None))
        self.actionLoop_settings.setText(_translate("MainWindow", "Loop settings", None))
        self.actionVolume.setText(_translate("MainWindow", "Volume", None))

        self.connect()

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

